Feature
latifa-wakili/landing-page pull request #1
Opened 2024-05-29 06:36 UTC by latifa-wakili

landing page project

2024-05-30 21:23 UTC, ahzamir requested changes
### Hi @latifa-wakili  🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code are passing the freecodecamp tests, but still you have to clean your code and add some changes to your README.md file.
  - Check the inline comments below for more details
  
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/latifa-wakili/landing-page/assets/96838030/fe2a8c80-dfdb-4767-a1a0-374db888c86f)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean
❌Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 21:23 UTC, ahzamir commented on index.html
Your HTML code is not clean and properly aligned. Please use 2 spaces for indentation instead of 4-3-1. Additionally, ensure that child elements are properly indented under their parent elements. Here's an example to help you:

**Incorrect:**
```html
<!DOCTYPE html>
<html>
    <head>
  <title>Page Title</title>
      </head>
    <body>
        <h1>This is a Heading</h1>
        <p>This is a paragraph.</p>
    </body>
</html>
```

**Correct:**
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p>This is a paragraph.</p>
  </body>
</html>
```

**Rule:** Each child element should be indented 2 spaces under its parent element for better readability and maintainability.
**Hint**: Go to the VSCode bottom right corner, you can see "Spaces: 4" (or a similar indicator). Click on that, then click on "Indent Using Spaces" and select 2. You can also use the gray color column lines to help you know where your parent and child elements should be.

2024-05-30 21:23 UTC, ahzamir commented on README.md
> +
- You have to close the code section just by adding 3 (```)

2024-05-30 21:23 UTC, ahzamir commented on README.md
> +```
- Here add the git clone your-project-ssh-key-link
- And then cd your-rep-name

2024-05-30 21:23 UTC, ahzamir commented on README.md
> +- Email: [example](saavenwakili@gmail.com)
- Remove the example and add your own name

2024-05-31 17:20 UTC, latifa-wakili commented on README.md
> +- Email: [example](saavenwakili@gmail.com)
@ahzamir sir i did what you said on last feedbacks please re reveiw now

2024-06-01 11:00 UTC, ahzamir approved these changes
### Hi @latifa-wakili 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/latifa-wakili/landing-page/assets/96838030/fe2a8c80-dfdb-4767-a1a0-374db888c86f)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-01 11:35 UTC, latifa-wakili commented on README.md
> +```
@ahzamir Now please re review it

2024-06-01 11:54 UTC, merged